lenguaje: go
go: "1.11"

stages:
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: deploy
      env:
        - GO111MODULE=on
      script:
        - GO111MODULE=off go get github.com/go-bindata/go-bindata/...
        - go-bindata -o assets.go template/
        - sed -i 's/package\ main/package\ graphqldoc/g' assets.go
        - cd cmd/
        - GOOS=linux GOARCH=amd64 go build -o graphqldoc.linux
        - GOOS=windows GOARCH=amd64 go build -o graphqldoc.windows.exe
        - GOOS=darwin GOARCH=amd64 go build -o graphqldoc.darwin
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t $DOCKER_USERNAME/graphqldoc ../
        - docker tag $DOCKER_USERNAME/graphqldoc $DOCKER_USERNAME/graphqldoc:$TRAVIS_TAG
        - docker push $DOCKER_USERNAME/graphqldoc:$TRAVIS_TAG
      deploy:
        provider: releases
        api_key: ${api_key}
        file:
          - graphqldoc.linux
          - graphqldoc.darwin
          - graphqldoc.windows.exe
        skip_cleanup: true
        on:
          all_branches: true
          tags: true
